name: CI

on:
  push:
    branches:
      - main
    paths:
     - "original.txt"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run job
        run: echo "Running Second file through github action using the reusable concepts."

  caller-reusable:
    uses: ./.github/workflows/original.yml

  call-reusable_from_another_repo:
    uses: Gunasekhar9347/gitactions-1/.github/workflows/blank.yml@main
    
